#ifndef ENTITY_H
#define ENTITY_H

#define ENTITY_COUNT 1024

typedef enum {
	COMPONENT_NONE = 0L,
	COMPONENT_POSITION = 1 << 1L,
	COMPONENT_RENDERABLE = 1 << 2L,
	COMPONENT_COLLIDABLE = 1 << 3L
} Component;

#endif