#ifndef ENTITY_H
#define ENTITY_H

#define ENTITY_COUNT 1024

typedef enum {
	COMPONENT_NONE = 0LL,
	COMPONENT_POSITION = 1 << 1LL,
	COMPONENT_RENDERABLE = 1 << 2LL,
	COMPONENT_COLLIDABLE = 1 << 3LL
} Component;

#endif