#ifndef RENDER_PASS_H
#define RENDER_PASS_H

typedef enum {
	RENDER_PASS_LIGHT_SOURCE,
	RENDER_PASS_WEAPON_BLOOM,
	RENDER_PASS_BLOOM_SOURCE,
	RENDER_PASS_WORLD_OVERLAY,
	RENDER_PASS_MAIN,
	RENDER_PASS_COUNT
} RenderPass;

#endif
